import 'package:drift/drift.dart';
import 'app_database.dart';

class SeedData {
  static List<CategoriesCompanion> getDefaultCategories() {
    final now = DateTime.now();
    return [
      CategoriesCompanion.insert(
        id: 'cat_food',
        name: 'Alimentación',
        icon: 'restaurant',
        color: '#FF5722',
        type: 'expense',
        displayOrder: const Value(1),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_transport',
        name: 'Transporte',
        icon: 'directions_car',
        color: '#2196F3',
        type: 'expense',
        displayOrder: const Value(2),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_home',
        name: 'Hogar',
        icon: 'home',
        color: '#4CAF50',
        type: 'expense',
        displayOrder: const Value(3),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_health',
        name: 'Salud',
        icon: 'local_hospital',
        color: '#F44336',
        type: 'expense',
        displayOrder: const Value(4),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_entertainment',
        name: 'Entretenimiento',
        icon: 'sports_esports',
        color: '#9C27B0',
        type: 'expense',
        displayOrder: const Value(5),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_clothing',
        name: 'Ropa',
        icon: 'checkroom',
        color: '#FF9800',
        type: 'expense',
        displayOrder: const Value(6),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_education',
        name: 'Educación',
        icon: 'school',
        color: '#00BCD4',
        type: 'expense',
        displayOrder: const Value(7),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_services',
        name: 'Servicios',
        icon: 'build',
        color: '#795548',
        type: 'expense',
        displayOrder: const Value(8),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_other',
        name: 'Otros',
        icon: 'category',
        color: '#9E9E9E',
        type: 'expense',
        displayOrder: const Value(9),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_salary',
        name: 'Salario',
        icon: 'work',
        color: '#4CAF50',
        type: 'income',
        displayOrder: const Value(10),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_freelance',
        name: 'Freelance',
        icon: 'laptop',
        color: '#2196F3',
        type: 'income',
        displayOrder: const Value(11),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_investment',
        name: 'Inversiones',
        icon: 'trending_up',
        color: '#FF9800',
        type: 'income',
        displayOrder: const Value(12),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_gift',
        name: 'Regalos',
        icon: 'card_giftcard',
        color: '#E91E63',
        type: 'income',
        displayOrder: const Value(13),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
      CategoriesCompanion.insert(
        id: 'cat_other_income',
        name: 'Otros Ingresos',
        icon: 'attach_money',
        color: '#9E9E9E',
        type: 'income',
        displayOrder: const Value(14),
        isDefault: const Value(true),
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }

  static List<SettingsCompanion> getDefaultSettings() {
    final now = DateTime.now();
    return [
      SettingsCompanion.insert(
        key: 'monthly_budget',
        value: '0',
        updatedAt: now,
      ),
      SettingsCompanion.insert(
        key: 'currency',
        value: 'PEN',
        updatedAt: now,
      ),
      SettingsCompanion.insert(
        key: 'theme',
        value: 'system',
        updatedAt: now,
      ),
      SettingsCompanion.insert(
        key: 'first_launch_date',
        value: DateTime.now().toIso8601String(),
        updatedAt: now,
      ),
    ];
  }

  static List<MovementsCompanion> getDefaultMovements() {
    final now = DateTime.now();
    return [
      MovementsCompanion.insert(
        id: 'mov_1',
        amount: 3500.0,
        description: 'Salario mensual',
        categoryId: 'cat_salary',
        date: DateTime(now.year, now.month, 1),
        type: 'income',
        notes: const Value.absent(),
        createdAt: DateTime(now.year, now.month, 1),
        updatedAt: DateTime(now.year, now.month, 1),
      ),
      MovementsCompanion.insert(
        id: 'mov_2',
        amount: 84.50,
        description: 'Supermercado',
        categoryId: 'cat_food',
        date: now.subtract(const Duration(days: 2)),
        type: 'expense',
        notes: const Value.absent(),
        createdAt: now.subtract(const Duration(days: 2)),
        updatedAt: now.subtract(const Duration(days: 2)),
      ),
      MovementsCompanion.insert(
        id: 'mov_3',
        amount: 15.99,
        description: 'Suscripción Netflix',
        categoryId: 'cat_entertainment',
        date: now.subtract(const Duration(days: 1)),
        type: 'expense',
        notes: const Value.absent(),
        createdAt: now.subtract(const Duration(days: 1)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      MovementsCompanion.insert(
        id: 'mov_4',
        amount: 1200.0,
        description: 'Pago Freelance',
        categoryId: 'cat_freelance',
        date: now.subtract(const Duration(days: 3)),
        type: 'income',
        notes: const Value.absent(),
        createdAt: now.subtract(const Duration(days: 3)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      MovementsCompanion.insert(
        id: 'mov_5',
        amount: 12.50,
        description: 'Viaje en Uber',
        categoryId: 'cat_transport',
        date: now.subtract(const Duration(days: 4)),
        type: 'expense',
        notes: const Value.absent(),
        createdAt: now.subtract(const Duration(days: 4)),
        updatedAt: now.subtract(const Duration(days: 4)),
      ),
      MovementsCompanion.insert(
        id: 'mov_6',
        amount: 89.99,
        description: 'Compras en Amazon',
        categoryId: 'cat_clothing',
        date: now.subtract(const Duration(days: 5)),
        type: 'expense',
        notes: const Value.absent(),
        createdAt: now.subtract(const Duration(days: 5)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      MovementsCompanion.insert(
        id: 'mov_7',
        amount: 65.0,
        description: 'Cena en Restaurante',
        categoryId: 'cat_food',
        date: now.subtract(const Duration(days: 8)),
        type: 'expense',
        notes: const Value.absent(),
        createdAt: now.subtract(const Duration(days: 8)),
        updatedAt: now.subtract(const Duration(days: 8)),
      ),
    ];
  }
}
